# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomsDeclaraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customs_file', models.FileField(upload_to='customs_delcaraction/')),
                ('customs_number', models.CharField(max_length=13)),
                ('filename', models.CharField(max_length=50)),
                ('upload_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
